// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH95RAVILZMSS30__pFYCK_uk9Q37iyvY',
    appId: '1:188178396244:web:240b9a34fb6f5ed4fc69c1',
    messagingSenderId: '188178396244',
    projectId: 'chit-chat-615f3',
    authDomain: 'chit-chat-615f3.firebaseapp.com',
    storageBucket: 'chit-chat-615f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5aNY5QFK_wpAuYAvTCyXQGlAFyZWxIhM',
    appId: '1:188178396244:android:21b2f8a646b9fff7fc69c1',
    messagingSenderId: '188178396244',
    projectId: 'chit-chat-615f3',
    storageBucket: 'chit-chat-615f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Ot-9R7gZVWbTnM6gZQfz_VW6xq_M06Q',
    appId: '1:188178396244:ios:a7e8fe2672b9f050fc69c1',
    messagingSenderId: '188178396244',
    projectId: 'chit-chat-615f3',
    storageBucket: 'chit-chat-615f3.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Ot-9R7gZVWbTnM6gZQfz_VW6xq_M06Q',
    appId: '1:188178396244:ios:a7e8fe2672b9f050fc69c1',
    messagingSenderId: '188178396244',
    projectId: 'chit-chat-615f3',
    storageBucket: 'chit-chat-615f3.firebasestorage.app',
    iosBundleId: 'com.example.chitChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH95RAVILZMSS30__pFYCK_uk9Q37iyvY',
    appId: '1:188178396244:web:e946b0d3e0e7d856fc69c1',
    messagingSenderId: '188178396244',
    projectId: 'chit-chat-615f3',
    authDomain: 'chit-chat-615f3.firebaseapp.com',
    storageBucket: 'chit-chat-615f3.firebasestorage.app',
  );
}
